//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrikiTeamWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FrikiTeamBDEntities4 : DbContext
    {
        public FrikiTeamBDEntities4()
            : base("name=FrikiTeamBDEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calle> Calle { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<CodigoEvento> CodigoEvento { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Evento_Usuario> Evento_Usuario { get; set; }
        public virtual DbSet<NumeroCasa> NumeroCasa { get; set; }
        public virtual DbSet<Organizador> Organizador { get; set; }
    }
}
